# Сборка Vue
FROM node:20 AS build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build


FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html
# Копируем как default.conf, а не nginx.conf
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
